apiVersion: v1
kind: Pod
metadata:
  name: random-generator
  labels:
    app: random-generator
spec:
  containers:

    - image: k8spatterns/random-generator:1.0
      name: main
      env:
        - name: LOG_FILE
          value: /logs/random.log
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /logs
          name: log-volume

    - image: k8spatterns/random-generator-exporter
      name: adapter
      env:
        - name: LOG_FILE
          value: /logs/random.log
      ports:
        - containerPort: 9889
          protocol: TCP
      volumeMounts:
        - mountPath: /logs
          name: log-volume

  volumes:
    - name: log-volume
      emptyDir: {}
