apiVersion: v1
kind: Service
metadata:
  name: random-generator-service
spec:
  selector:
    app: random-generator
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080