apiVersion: v1
kind: Pod
metadata:
  name: random-generator
  labels:
    app: random-generator
spec:
  containers:

    - image: k8spatterns/random-generator:1.0
      name: main
      env: []
      ports:
        - containerPort: 8080
          protocol: TCP
      